# Generated by Django 4.0.1 on 2023-02-28 07:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('App_Posts', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='captioin',
            new_name='caption',
        ),
    ]
